---

- name: Fetch genesis.json
  fetch: "src=/home/dexd/.dex/config/genesis.json dest={{GENESISFILE}} flat=yes"
  run_once: yes
  become: yes
  become_user: dexd

- name: Fetch config.toml
  fetch: "src=/home/dexd/.dex/config/config.toml dest={{CONFIGFILE}} flat=yes"
  run_once: yes
  become: yes
  become_user: dexd

